- name: Install System Packages 2 (lua, unzip, libtool,  gettext)
  become: true
  package:
    name:
      [
        "base-devel",
        "intel-ucode",
        "tmux",
        "neovim",
        "stow",
        "ripgrep",
        "fzf",
        "ntfs-3g",
        "iwd",
        "git",
        "curl",
        "wget",
        "man",
        "tldr",
        "lua",
        "jq",
        "thefuck",
        "zip",
        "unzip",
        "libtool",
        "gettext",
        "xdg-user-dirs",
        "xorg-xwayland",
        "qt5-wayland",
        "networkmanager",
        "blueman",
        "podman",
        "acpi",
        "android-tools",
        "mitmproxy",
      ]
  tags:
    - install
    - core

- name: Install Hyprland and required packages
  become: true
  package:
    name:
      [
        "hyprland",
        "hyprpaper",
        "xdg-desktop-portal-hyprland",
        "kitty",
        "alacritty",
        "waybar",
        "pamixer",
        "wofi",
        "brightnessctl",
        "wl-clipboard",
        "slurp",
        "grim",
        "zathura",
        "zathura-cb",
        "zathura-djvu",
        "zathura-pdf-poppler",
        "screenkey",
        "network-manager-applet",
        "polkit-gnome",
        "nautilus",
        "uget",
        "vlc",
      ]
  tags:
    - install
    - core

- name: Install Useful Fonts
  become: true
  package:
    name:
      [
        "awesome-terminal-fonts",
        "noto-fonts",
        "noto-fonts-cjk",
        "noto-fonts-emoji",
        "noto-fonts-extra",
        "otf-font-awesome",
        "ttf-fira-code",
        "ttf-firacode-nerd",
        "ttf-font-awesome",
        "ttf-hack",
        "ttf-jetbrains-mono",
        "ttf-jetbrains-mono-nerd",
      ]
  tags:
    - install
    - ui
    - core

- name: Install icons and themes and other related tools
  become: true
  package:
    name: [
        # "lxappearance",
        "kvantum",
        "qt5ct",
        "qt6ct",
        "kvantum-theme-materia",
        "nwg-look",
        "materia-gtk-theme",
        "materia-kde",
        "papirus-icon-theme",
      ]
  tags:
    - install
    - ui
    - core
